### ISSUE TITLE
Keeping the user always in sync with the LDAP server

### ISSUE THREAD

**Issue by johnboc** [jotaelesalinas/laravel-adminless-ldap-auth#29]
I have moved the 
`$sync_attrs = $this->retrieveSyncAttributes($username);`
out and below 
`if (!$user)`
as per the comments but the attributes don't sync.

A quick test is to change the name of a logged in user in the database and then log them in. The code doesn't update the user's name. 

The database updates when this line executes
`$this->guard()->login($user, true);`
but it only fills the field values when the user first logins in.

By the way, this is an excellent explanation of how to combine Laravel and ldap. Well done.

**Comment by jotaelesalinas** [comment]
I created a composer package out of this tutorial. You can give it a try.
