### ISSUE TITLE
I am not able to login with your give credentials 

### ISSUE THREAD

**Issue by SourabhDogra1511** [jotaelesalinas/laravel-adminless-ldap-auth#36]
First of all thanks to providing such a wonderful tutorial of ldap, I followed all the steps and successfully executed,
But when I try to login with your given credentials, I am not able to log in.
I will try with my local OpenLDAP credentials, but it not works can you please help me out what exactly the issue.

Thanks for your help

**Comment by jotaelesalinas** [comment]
I created a composer package out of this tutorial. You can give it a try.
