### ISSUE TITLE
Exception with message 'AdminlessLdapUser: Could not find keyName.'

### ISSUE THREAD

**Issue by joshua87327** [jotaelesalinas/laravel-adminless-ldap-auth#39]
Hi! I had follow your project to try the Auth::attempt(). But I always get "Exception with message 'AdminlessLdapUser: Could not find keyName.'" message. Which part did I do wrong?

**Comment by jotaelesalinas** [comment]
The error is generated here: <https://github.com/jotaelesalinas/laravel-adminless-ldap-auth/blob/803f82ccb07f86bcae8f839abcb4b08221f26dbf/src/LdapUser.php#L21>

Is the config key `auth.auth_user_key` defined?

Also, do you have the lastest version? The class is not named `AdminlessLdapUser` any more, but `LdapUser`.

**Comment by joshua87327** [comment]
I just start a new laravel project today. Does config key set in .env? Or where should I set the config key.

**Comment by jotaelesalinas** [comment]
The configuration part of the instructions is mandatory. The package will not work if it is not properly configured.
