### ISSUE TITLE
Exception with message 'LdapUser: missing config variable "auth.auth_user_key".'

### ISSUE THREAD

**Issue by ken-colvin** [jotaelesalinas/laravel-adminless-ldap-auth#41]
- I installed you package and followed the instructions to use the default ldap.forumsys.com 
- I am using Laravel Framework 6.18.18 and getting this error
- Here is where I am getting the error:

```
[site]$ php artisan tinker
Psy Shell v0.10.4 (PHP 7.3.19 — cli) by Justin Hileman
>>> Auth::attempt(['username' => 'einstein', 'password' => ''])
Exception with message 'LdapUser: missing config variable "auth.auth_user_key".'

```
![image](https://user-images.githubusercontent.com/8449843/84275822-273a5600-aaf7-11ea-9573-0ff8692858cd.png)

**Comment by jotaelesalinas** [comment]
Hi @ken-colvin ! This error means that the config variable `'auth_user_key'` is not set inside `config/auth.php` (or it is empty).

**Comment by jotaelesalinas** [comment]
Hi @ken-colvin . Have you been able to solve the issue?

**Comment by ken-colvin** [comment]
- Yes I resolved, thanks.  
- I had to add auth.auth_user_key=env('AUTH_USER_KEY') and set this in .env
- That was missing from your instructions.

**Comment by jotaelesalinas** [comment]
I'm glad you found the solution. I think it is in the instructions, tough: the last parageaph of the section 
"[Modify config/auth.php](https://github.com/jotaelesalinas/laravel-adminless-ldap-auth#modify-configauthphp)".

**Comment by ken-colvin** [comment]
It is there. Good job on this software.
